### ISSUE TITLE
Add support for Visual Studio Preview

### ISSUE THREAD

**Issue by nil-ref** [SConsProject/scons#4190] opened 2022-07-14 03:43 UTC
```
SCons/Tool/MSCommon# diff -u vc.py vc_new.py
--- vc.py       2022-07-14 11:38:22.632212900 +0800
+++ vc_new.py   2022-07-14 11:37:42.998109300 +0800
@@ -705,7 +705,7 @@
     debug('VSWHERE: %s', vswhere_path)
     for vswhere_version_args in vswhere_version:

-        vswhere_cmd = [vswhere_path] + vswhere_version_args + ["-property", "installationPath"]
+        vswhere_cmd = [vswhere_path] + ["-prerelease"] + vswhere_version_args + ["-property", "installationPath"]

         debug("running: %s", vswhere_cmd)
```

**Comment by bdbaddog** [comment] 2022-07-14 11:51
Duplicate of #4048 

Since users may not always want to run prerelease this patch isn't something we can apply.
Note that there's a big PR in flight to address this and other issues. #4174

**Closed as completed by bdbaddog** 2022-07-14 11:51 UTC
